In [17]:
import nltk
import pandas as pd
import numpy as np
import matplotlib 
import matplotlib.pyplot as plt

In [18]:
from nltk.tokenize import word_tokenize, sent_tokenize

In [19]:
from nltk.tag import pos_tag

In [20]:
from konlpy.tag import Okt
okt=Okt()

In [21]:
token=okt.morphs("나는 데이터 분석을 배운다")
token

['나', '는', '데이터', '분석', '을', '배운다']

In [22]:
word2index={}
for v in token:
    if v not in word2index.keys():
        word2index[v]=len(word2index)
print(word2index)

{'나': 0, '는': 1, '데이터': 2, '분석': 3, '을': 4, '배운다': 5}


In [23]:
#원핫 인코딩

def ohe(word,word2index):
    ohv=[0]*(len(word2index)) #[0]을 길기만큼 반복
    print(ohv)
    index=word2index[word]
    ohv[index]=1 #2번째 인덱스 값을 1로 변경
    return ohv

ohe("데이터",word2index)

[0, 0, 0, 0, 0, 0]


[0, 0, 1, 0, 0, 0]

In [ ]:
#stopword 처리 (불용어 처리) : 의미 없는 단어 처리

In [5]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [24]:
from nltk.corpus import stopwords

In [25]:
ex="I don't know where it is"
sw=stopwords.words("english")
word_tokens=word_tokenize(ex)

res=[]
for w in word_tokens:
    if w not in sw:
        res.append(w)
print(res)

['I', "n't", 'know']


In [26]:
ex="오늘은 금요일 입니다. 졸면 안 돼. 오늘만 참자"
stop_words="안 돼 참자"
sw=stop_words.split(" ")
word_tokens=word_tokenize(ex)

res=[]
for w in word_tokens:
    if w not in sw:
        res.append(w)
print(res)

['오늘은', '금요일', '입니다', '.', '졸면', '.', '오늘만']


In [27]:
mail=[
    ['형님 어제 나이트 왜 안왔어요?',1],
    ['절호의 찬스, 놓치면 평생 휘회',1],
    ['잘 지냈어요? 오랜만',0]]
col=['메일제목','스팸여부']
df=pd.DataFrame(mail,columns=col)
df

메일제목  스팸여부
0  형님 어제 나이트 왜 안왔어요?     1
1  절호의 찬스, 놓치면 평생 휘회     1
2        잘 지냈어요? 오랜만     0

In [28]:
import re

In [29]:
token=re.sub("(\.)","","오늘은 초여름의 날씨를 볼 수 있겠습니다.") #점기호 삭제
token

'오늘은 초여름의 날씨를 볼 수 있겠습니다'

In [31]:
okt=Okt()

In [36]:
toekn=okt.morphs(token)
toekn

['오늘', '은', '초여름', '의', '날씨', '를', '볼', '수', '있겠습니다']

In [41]:
w2i={}
BOW=[]

for v in token:
    if v not in w2i.keys():
        w2i[v]=len(w2i)
        BOW.insert(len(w2i)-1,1)
    else:
        i=w2i.get(v)
        BOW[i]=BOW[i]+1
print(w2i)
print(BOW)

{'오': 0, '늘': 1, '은': 2, ' ': 3, '초': 4, '여': 5, '름': 6, '의': 7, '날': 8, '씨': 9, '를': 10, '볼': 11, '수': 12, '있': 13, '겠': 14, '습': 15, '니': 16, '다': 17}
[1, 1, 1, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [42]:
from sklearn.feature_extraction.text import CountVectorizer

In [43]:
text=["you know I want your love. becaues I love you."]

vector=CountVectorizer() #두 글자 이상에 대해서만 생성 (i 는 제외됨)
vector.fit_transform(text).toarray()

array([[1, 1, 2, 1, 2, 1]], dtype=int64)

In [44]:
vector.vocabulary_

{'you': 4, 'know': 1, 'want': 3, 'your': 5, 'love': 2, 'becaues': 0}

In [47]:
vect=CountVectorizer(stop_words=['the','a','an','not','is'])
test=["Family is not an important thing. It's everything."]

vect.fit_transform(text).toarray()

array([[1, 1, 2, 1, 2, 1]], dtype=int64)

In [50]:
text=[
      "you know I want your love",
      "I like you",
      "what should I do"
]

vector=CountVectorizer()
print(vector.fit_transform(text).toarray())
print(vector.vocabulary_)

[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [53]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [56]:
text=[
      "you know I want your love",
      "I like you",
      "what should I do"
]

tfidf=TfidfVectorizer().fit(text)

print(tfidf.fit_transform(text).toarray())
print(tfidf.vocabulary_)

[[0.         0.46735098 0.         0.46735098 0.         0.46735098
  0.         0.35543247 0.46735098]
 [0.         0.         0.79596054 0.         0.         0.
  0.         0.60534851 0.        ]
 [0.57735027 0.         0.         0.         0.57735027 0.
  0.57735027 0.         0.        ]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}
